# Generated by Django 5.0.4 on 2024-06-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "text",
                    models.TextField(max_length=1024, verbose_name="message text"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("bot", "Bot"),
                            ("user", "User"),
                            ("system", "System"),
                        ],
                        default="user",
                        max_length=10,
                        verbose_name="role",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messages",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "db_table": "sessions",
            },
        ),
    ]
