name: Linter

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
    linter:
        name: Lint Code
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Super-linter
          uses: super-linter/super-linter@latest
          env:
            DISABLE_ERRORS: true
            VALIDATE_PYTHON: true
            VALIDATE_HTML: false
            VALIDATE_JAVASCRIPT_ES: false
            VALIDATE_JAVASCRIPT_STANDARD: false
            VALIDATE_CSS: false
            DEFAULT_BRANCH: dev
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}